### ISSUE TITLE
The capability associated with "GROUP_ACTIVITIES" could not be determined. 

### ISSUE THREAD

**Issue by MidnightAck** [tokorom/SharePlaySample#1]
Hi, I encontered a problem that the Signing & Capabilities show the following error:

`The capability associated with "GROUP_ACTIVITIES" could not be determined. Please file a bug report at https://feedbackassistant.apple.com and include the Update Signing report from the Report navigator.`

I haven't find a solution online, is there anything I can do to solve this?Thx

**Comment by tokorom** [comment]
@CrowFea 

I am able to add `Capability` to `Group Activities` without any problems, and I am able to build and run debugging.

with Xcode Version 13.0 beta 3 (13A5192i)

**Comment by MidnightAck** [comment]
THX! It turns out I should enroll Apple Developer Project First.It works out for me now.
